version: '3.8'
services:
  db:
    image: mariadb:10.7.4
    restart: always
    environment:
      MARIADB_DATABASE: max_inventory
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: rootroot
    ports:
      - '3307:3306'
    volumes: 
      - data:/var/lib/mysql
  
volumes:
  data:
