version: '3.8'
services:
  db:
    image: mariadb:10.7.4
    restart: always
    environment:
      MYSQL_DATABASE: max_inventory
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot
    ports:
      - '3306:3306'
    volumes: 
      - data:/var/lib/mysql
  
volumes:
  data:
